env:
  jest: true
  browser: true

parser: 'babel-eslint'

parserOptions:
  ecmaVersion: 9
  sourceType: 'module'
  allowImportExportEverywhere: false

settings:
  react:
    version: 16.8.6

extends: [
  '../../../.eslintrc.yml',
  'plugin:jest/recommended',
  'plugin:react/recommended',
]

rules:
  react/prop-types: false
  react/display-name: false
